# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 15:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Institute',
                'verbose_name_plural': 'Institutes',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Offer type',
                'verbose_name_plural': 'Offer types',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=48, verbose_name='Lastname')),
                ('other_names', models.CharField(max_length=128, verbose_name='Other names')),
                ('title_before', models.CharField(blank=True, max_length=128, null=True, verbose_name='Title before')),
                ('title_after', models.CharField(blank=True, max_length=128, null=True, verbose_name='Title after')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('anotation', models.TextField(verbose_name='Synopsis')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='Published')),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_as_depositor', to='acatto.Person', verbose_name='Depositor')),
                ('tt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_as_tt', to='acatto.Person', verbose_name='Transfer adviser')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='acatto.Institute')),
                ('members', models.ManyToManyField(to='acatto.Person')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='X_Product_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='acatto.Person', verbose_name='Author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='acatto.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product author',
                'verbose_name_plural': 'Product authors',
            },
        ),
        migrations.CreateModel(
            name='X_Product_Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='acatto.Branch', verbose_name='Branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='acatto.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product_Branch',
                'verbose_name_plural': 'Product_Branches',
            },
        ),
        migrations.CreateModel(
            name='X_Product_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='acatto.Offer', verbose_name='Offer type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='acatto.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product offer type',
                'verbose_name_plural': 'Product offer types',
            },
        ),
        migrations.CreateModel(
            name='X_Product_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='acatto.Product', verbose_name='Product')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='acatto.Team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Product team',
                'verbose_name_plural': 'Product teams',
            },
        ),
        migrations.CreateModel(
            name='X_Team_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='acatto.Person', verbose_name='Author')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='acatto.Team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team membership',
                'verbose_name_plural': 'Team memberships',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='acatto.Industry'),
        ),
    ]
