# Generated by Django 2.0 on 2017-12-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('acatto', '0001_initial'), ('acatto', '0002_product_author'), ('acatto', '0003_auto_20171213_1359'), ('acatto', '0004_team_memebers'), ('acatto', '0005_auto_20171213_1405'), ('acatto', '0006_remove_team_members'), ('acatto', '0007_team_members'), ('acatto', '0008_product_content'), ('acatto', '0009_remove_product_author'), ('acatto', '0010_auto_20171219_1406')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Obor',
                'verbose_name_plural': 'Obory',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Odvětví',
                'verbose_name_plural': 'Odvětví',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Ústav',
                'verbose_name_plural': 'Ústavy',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Typ nabídky',
                'verbose_name_plural': 'Typy nabídek',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt', models.BooleanField(default=True)),
                ('depositor', models.BooleanField(default=True)),
                ('author', models.BooleanField(default=True)),
                ('lastname', models.CharField(max_length=48)),
                ('other_names', models.CharField(max_length=128)),
                ('title_before', models.CharField(blank=True, max_length=128, null=True)),
                ('title_after', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('anotation', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_as_depositor', to='acatto.Person')),
                ('tt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_as_tt', to='acatto.Person')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='acatto.Institute')),
            ],
            options={
                'verbose_name': 'Tým (Výzkumná skupina)',
                'verbose_name_plural': 'Týmy (Výzkumné skupiny)',
            },
        ),
        migrations.CreateModel(
            name='X_Product_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='acatto.Person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='acatto.Product')),
            ],
            options={
                'verbose_name': 'Autorství produktu',
                'verbose_name_plural': 'Autorství produktu',
            },
        ),
        migrations.CreateModel(
            name='X_Product_Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='acatto.Branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='acatto.Product')),
            ],
            options={
                'verbose_name': 'Obor produktu',
                'verbose_name_plural': 'Obory produktu',
            },
        ),
        migrations.CreateModel(
            name='X_Product_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='acatto.Offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='acatto.Product')),
            ],
            options={
                'verbose_name': 'Typ nabídky produktu',
                'verbose_name_plural': 'Typy nabídek produktu',
            },
        ),
        migrations.CreateModel(
            name='X_Product_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='acatto.Product')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='acatto.Team')),
            ],
            options={
                'verbose_name': 'Tým produktu',
                'verbose_name_plural': 'Týmy produktu',
            },
        ),
        migrations.CreateModel(
            name='X_Team_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='acatto.Person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='acatto.Team')),
            ],
            options={
                'verbose_name': 'Příslušnost k týmu',
                'verbose_name_plural': 'Příslušnost k týmu',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='acatto.Industry'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='author',
        ),
        migrations.RemoveField(
            model_name='person',
            name='depositor',
        ),
        migrations.RemoveField(
            model_name='person',
            name='tt',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='acatto.Person'),
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(),
        ),
    ]
