# Generated by Django 2.0 on 2017-12-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acatto', '0001_squashed_0010_auto_20171219_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
    ]
