# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 17:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acatto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en_US', 'english'), ('cs_CZ', 'czech')], max_length=5)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('anotation', models.TextField(verbose_name='Synopsis')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_localizations', to='acatto.Product', verbose_name='Product')),
            ],
        ),
    ]
