# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acatto', '0002_productloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='anotation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
    ]
