# Generated by Django 2.0 on 2017-12-22 12:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acatto', '0003_product_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'verbose_name': 'Institute', 'verbose_name_plural': 'Institutes'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Offer type', 'verbose_name_plural': 'Offer types'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='x_product_author',
            options={'verbose_name': 'Product author', 'verbose_name_plural': 'Product authors'},
        ),
        migrations.AlterModelOptions(
            name='x_product_branch',
            options={'verbose_name': 'Product_Branch', 'verbose_name_plural': 'Product_Branches'},
        ),
        migrations.AlterModelOptions(
            name='x_product_offer',
            options={'verbose_name': 'Product offer type', 'verbose_name_plural': 'Product offer types'},
        ),
        migrations.AlterModelOptions(
            name='x_product_team',
            options={'verbose_name': 'Product team', 'verbose_name_plural': 'Product teams'},
        ),
        migrations.AlterModelOptions(
            name='x_team_author',
            options={'verbose_name': 'Team membership', 'verbose_name_plural': 'Team memberships'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=48, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_names',
            field=models.CharField(max_length=128, verbose_name='Other names'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_after',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Title after'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_before',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Title before'),
        ),
        migrations.AlterField(
            model_name='product',
            name='anotation',
            field=models.TextField(verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='depositor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_as_depositor', to='acatto.Person', verbose_name='Depositor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_as_tt', to='acatto.Person', verbose_name='Transfer adviser'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='x_product_author',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='acatto.Person', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='x_product_author',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='acatto.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='x_product_branch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='acatto.Branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='x_product_branch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='acatto.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='x_product_offer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='acatto.Offer', verbose_name='Offer type'),
        ),
        migrations.AlterField(
            model_name='x_product_offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='acatto.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='x_product_team',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='acatto.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='x_product_team',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='acatto.Team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='x_team_author',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='acatto.Person', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='x_team_author',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='acatto.Team', verbose_name='Team'),
        ),
    ]
