# Generated by Django 2.0.1 on 2018-01-22 15:19

import django.contrib.postgres.indexes
from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acatto', '0003_auto_20180112_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='acatto_offer_i18n_gin'),
        ),
    ]
